### ISSUE TITLE
phoebus: documentation cannot be built on arm64/aarch64 Linux

### ISSUE THREAD

**Issue by eddybl** [epics-training/training-vm#13]
Trying to set up the VM on an arm/aarch64 architecture I encountered an issue in building the Phoebus documentation. The following task in the ansible configuration fails:

```yml
- name: Build the documentation and help
  command: mvn clean verify -P sphinx -N
  become: true
  args:
    chdir: /opt/epics-tools/lib/phoebus/
  environment:
    JAVA_HOME: "{{ java_home }}"
    MVN_HOME: "{{ mvn_home }}"
    PATH: "{{ java_home }}/bin:{{ mvn_home }}/bin:{{ ansible_env.PATH }}"
  when: phoebus_repo.changed | bool
```

## Workaround

The workaround is to comment out the above block in the `vm-training/ansible/roles/epics-tools/tasks/build_phoebus.yml` file. The only impact is that while you run Phoebus inside the VM, the inline documentation/help is not available. Phoebus itself will work.

## Issue

The reason that this fails is because for building the documentation with Sphinx the [Sphinx Maven plugin](https://github.com/trustin/sphinx-maven-plugin) is used, which depends on these pre-built sphinx binary: [sphinx-binary](https://github.com/trustin/sphinx-binary) which lacks support for linux-aarch64. Both modules have not seen any new release over the last three years, so it would probably be nice to figure out a way to use Sphinx itself more directly without these wrapper plugins. Not sure if the actual phoebus client has the same issue

**Comment by shroffk** [comment]
Hmm...
While is it great to have the help documentation built into the product it should be perfectly acceptable to skip it.

Can you try the following

```
- name: Detect system architecture
  ansible.builtin.set_fact:
    is_arm: "{{ ansible_architecture in ['aarch64'] }}"

- name: Build the documentation and help
  command: mvn clean verify -P sphinx -N
  become: true
  args:
    chdir: /opt/epics-tools/lib/phoebus/
  environment:
    JAVA_HOME: "{{ java_home }}"
    MVN_HOME: "{{ mvn_home }}"
    PATH: "{{ java_home }}/bin:{{ mvn_home }}/bin:{{ ansible_env.PATH }}"
when: (phoebus_repo.changed | bool) and (not is_arm)
```
